version: '3'

services:
  tor-1:
    container_name: 'tor-1'
    image: 'pickapp/tor-proxy:latest'
    environment:
      - IP_CHANGE_SECONDS=15
    restart: always
  tor-2:
    container_name: 'tor-2'
    image: 'pickapp/tor-proxy:latest'
    environment:
      - IP_CHANGE_SECONDS=15
    restart: always
  tor-3:
    container_name: 'tor-3'
    image: 'pickapp/tor-proxy:latest'
    environment:
      - IP_CHANGE_SECONDS=15
    restart: always
  tor-4:
    container_name: 'tor-4'
    image: 'pickapp/tor-proxy:latest'
    environment:
      - IP_CHANGE_SECONDS=15
    restart: always
  tor-5:
    container_name: 'tor-5'
    image: 'pickapp/tor-proxy:latest'
    environment:
      - IP_CHANGE_SECONDS=15
    restart: always
  multitool:
    image: praqma/network-multitool

networks:
  default:
      name: adversea